# Generated by Django 5.1.3 on 2024-11-17 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
    ]
